name: Deployment demo
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Build container containing gems with Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::421736311596:role/EcrRoleCdkStack-ApplicationDeployerRoleA9F8749A-YBDSQ9174Q75
          aws-region: ap-southeast-2
          role-session-name: githubaction
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build tag and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: urlshortener
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPO/$ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REPO/$ECR_REGISTRY:$IMAGE_TAG



